import { Email } from "./email";

export const EMAILS: Email[] = [
  new Email(
    1,
    'gerard.ford@amazzon.com',
    'moi@gmail.com',
    'Information : Livraison de votre colis',
    'Votre commande Amazon n’a pas été livrée et a été remise au point colis, si vous ne la réclamez pas avant 48h en cliquant sur ce lien, elle ne vous sera pas remise.',
    'Vous n’avez pas payé les frais de livraison, vous pouvez le faire en cliquant sur ce lien',
    'https://amazzon.fr/mon-compte/mes-livraisons',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/1280px-Amazon_logo.svg.png',
    true,
    'Vendredi, 19h:30',
    'Gerard Ford',
    'facture.pdf',
    'pdf',
    '70 mo',
    false,
    'Il faut faire bien attention au nom !'
  ),

  new Email(
    2,
    'carefour-noreply@gmail.com',
    'moi@gmail.com',
    'Félicitation ! Vous remportez un iPhone',
    'Comme vous avez fait vos courses dans un établissement Carrefour de Seine-et-Marne au cours des 3 derniers mois, vous avez été inscrit à un tirage au sort dont le prix gagnant est un iPhone dernière génération.',
    'Cliquez sur le lien pour récupérer votre prix !',
    'https://www.carefour.com/reclamer-prix',
    'https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/Logo_Carrefour.svg/1200px-Logo_Carrefour.svg.png',
    true,
    'Vendredi, 18h:26',
    'Carrefour',
    'voucher.pdf',
    'pdf',
    '1 gb',
    false,
    'Cette offre était trop belle pour être vraie !'
  ),

  new Email(
    3,
    'support@msupdate.net',
    'moi@gmail.com',
    'Nouvelle connexion detectée',
    'Quelqu’un s’est connecté à votre compte depuis un nouvel appareil à Paris.',
    'Si vous n’êtes pas à l’origine de cette connexion cliquez sur le lien suivant :',
    'https://www.microsoft.com/account',
    'https://news.microsoft.com/wp-content/uploads/prod/sites/113/2017/06/Microsoft-logo_rgb_c-gray-768x344.png',
    false,
    'Vendredi, 15h:04',
    'Microsoft Support',
    '',
    'txt',
    '50 ko',
    false,
    'Rien d’anormal dans ce mail'
  ),

  new Email(
    4,
    'support@entreprise.net',
    'moi@gmail.com',
    'Security Update',
    'Bonjour, vous devez télécharger ce nouvel anti-virus pour garder votre appareil sécurisé.',
    'Télécharger le nouvel anti-virus :',
    'https://www.avasts.com',
    'https://www.codeur.com/blog/wp-content/uploads/2016/03/ge%CC%81ome%CC%81trique-1024x618.jpg',
    true,
    'Jeudi, 19h:30',
    'Support',
    'anti-virus.exe',
    'exe',
    '86 mo',
    false,
    'Il ne faut jamais télécharger de .exe'
  ),

  new Email(
    5,
    'finances.publiques@zodiac.fr',
    'moi@gmail.com',
    'Nouveau virement sur votre compte',
    'Bonjour, Un nouveau virement a été effectué sur votre compte.',
    'cliquez ici pour vous identifier et accéder à vos dernières opérations bancaires :',
    'https://www.finances-p.com/mon-compte/',
    'https://www.economie.gouv.fr/files/styles/blocs_mis_en_avant/public/files/directions_services/recrutement/Blocs%20essentiels/BlocDGFIP.jpg',
    true,
    'Mercredi, 11h:30',
    'Finances Publiques',
    '',
    'txt',
    '48 ko',
    false,
    'Il est préférable d’accéder à son compte depuis une application sécurisé'
  ),

  new Email(
    6,
    'service-client@orange.fr',
    'moi@gmail.com',
    'Information - Programme fidélité',
    'Connaissez-vous les avantages du programme de fidélité Orange ?',
    'Cliquez sur le lien pour profiter des avantages de notre programme fidélité :',
    'https://www.orange.fr/mon-compte/fidelite',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Orange_logo.svg/1200px-Orange_logo.svg.png',
    false,
    'Mercredi, 11h:37',
    'Service Free',
    '',
    'png',
    '86 mo',
    false,
    'Ce mail n’est pas frauduleux'
  ),

  new Email(
    7,
    'microsoftoutlook@dghdgeh.us',
    'moi@gmail.com',
    'Votre mot de passe arrive à expiration',
    'Votre mot de passe ne respecte plus les réglementations, votre compte va être désactivé.',
    'Cliquez sur le lien pour mettre à jour vos identifiants :',
    'https://www.outlouk.com/connexion',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg/800px-Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg.png',
    true,
    'Mercredi, 9h:54',
    'Microsoft Outlook',
    '',
    'pdf',
    '86 mo',
    false,
    'Attention au lien qui ne redige pas vers la bonne page'
  ),

  new Email(
    8,
    'support@laboncoin.fr',
    'moi@gmail.com',
    'Défaut de paiement',
    'Bonjour, le colis ne pourra pas être expédié en raison d’une erreur de paiement. Votre colis va donc être immobilisé.',
    'Veuillez suivre la procédure ci dessous :',
    'https://www.laboncoin.com/connexion/',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg/800px-Microsoft_Office_Outlook_%282018%E2%80%93present%29.svg.png',
    true,
    'Mardi, 14h:45',
    'Support Leboncoin',
    'procedure.pdf',
    'pdf',
    '84 mo',
    false,
    'Le lien n’était pas correct !'
  ),

  new Email(
    9,
    'associationnoe@info.noe.org',
    'moi@gmail.com',
    'Aidez nous à protéger les espèces menacées',
    'La population de grands fauves a baissé de 66% dans cette zone depuis 1990 à cause du braconnage.',
    'Aidez nous à lutter contre cette hémoragie en faisant un don :',
    'https://www.info.noe.org/faire-un-don',
    'https://static.vecteezy.com/system/resources/previews/027/077/205/original/pray-hand-gesture-color-2d-illustrations-png.png',
    false,
    'Mardi, 11h:12',
    'Arnaud Greth',
    'image.png',
    'png',
    '37 mo',
    false,
    'Ce mail n’est pas frauduleux'
  ),

  new Email(
    10,
    'service-client@free.fr',
    'moi@gmail.com',
    'Votre compte est peut être menacé',
    'Votre compte à été bloqué en raison d’un grand nombre de tentative de connexion.',
    'Vous pouvez débloquer votre compte en cliquant sur le lien ci dessous :',
    'https://www2.free.fr/unlock-account',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Free_logo.svg/1200px-Free_logo.svg.png',
    false,
    'Mardi, 11h:12',
    'Service Free',
    '',
    'png',
    '49 mo',
    false,
    'Attention au www2 qui redirige vers une autre page !'
  ),
];